name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Deploy to production
        uses: matheusvanzan/sshpass-action@v2
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.MY_SECRET_NAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          run: |
            cd ${{ secrets.PROJECT_PATH }}
            git pull origin main
            # Add additional deployment commands here